"""empty message

Revision ID: 0f6f40a7849f
Revises: ec19ca671512
Create Date: 2023-12-11 16:36:57.146593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6f40a7849f'
down_revision = 'ec19ca671512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('python_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('python_question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_text', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option1', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option2', sa.VARCHAR(length=255), nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
