"""empty message

Revision ID: 1548d595051b
Revises: 6d1aa68e304f
Create Date: 2023-12-21 13:20:39.058524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1548d595051b'
down_revision = '6d1aa68e304f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_code', schema=None) as batch_op:
        batch_op.drop_column('question')

    # ### end Alembic commands ###
