"""empty message

Revision ID: 1886ae6f8a06
Revises: c5de0dd9d4c9
Create Date: 2023-12-04 13:19:42.192946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1886ae6f8a06'
down_revision = 'c5de0dd9d4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
