"""empty message

Revision ID: 6d1aa68e304f
Revises: 0f6f40a7849f
Create Date: 2023-12-11 16:52:16.410271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6d1aa68e304f'
down_revision = '0f6f40a7849f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.alter_column('options',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.alter_column('options',
               existing_type=sqlite.JSON(),
               nullable=False)

    # ### end Alembic commands ###
