"""Add coding_score column to user table

Revision ID: 7db71a223a43
Revises: 1548d595051b
Create Date: 2023-12-22 11:56:16.535549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db71a223a43'
down_revision = '1548d595051b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coding_score', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_code', schema=None) as batch_op:
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('coding_score')

    # ### end Alembic commands ###
