"""empty message

Revision ID: c5de0dd9d4c9
Revises: 1f7371f4b56b
Create Date: 2023-11-29 13:42:13.274279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5de0dd9d4c9'
down_revision = '1f7371f4b56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('resume_data')
        batch_op.drop_column('resume_filename')

    # ### end Alembic commands ###
